disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- force_cast
- force_unwrapping
- force_try

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - submissionIosPemulaDicodingTests/submissionIosPemulaDicodingTests

identifier_name:
    allowed_symbols: "_"
    min_length: 500
    max_length: 1000

type_name:
    allowed_symbols: "_"
    min_length: 2
    max_length: 40

file_length:
    warning: 1000
    error: 1500
