disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- force_cast
- force_unwrapping
- force_try

type_name:
- allowed_symbols: "_"

identifier_name:
- allowed_symbols: "_"
